## Numpy

The NumPy package provides tools for mathematical computations in Python. 

**For example:** NumPy includes functions to perform common linear algebra operations, fast fourier transforms, and statistics.

### How to import NumPy

In [1]:
import numpy as np

### Array fundamentals

NumPy provides a multidimensional array object, conceptually similar to a list, consisting of an ordered set of elements of the same type.

In [1]:

## Summing arrays vs summing lists.

import numpy as np

list1 = [15.5, 25.11, 19.0]
list2 = [12.2, 1.3, 6.38] 

# Create two 1-dimensional (1D) arrays
# with the elements of the above lists
array1 = np.array(list1)
array2 = np.array(list2)

# Concatenate two lists
print('Concatenation of list1 and list2 =', end=' ')
print(list1 + list2)
print()

# Sum two lists
print('Sum of list1 and list2 =', end=' ')
for i in range(len(list1)):
    print(list1[i] + list2[i], end=' ')  
print('\n')


Concatenation of list1 and list2 = [15.5, 25.11, 19.0, 12.2, 1.3, 6.38]

Sum of list1 and list2 = 27.7 26.41 25.38 



In [2]:
# Sum two 1D arrays
print('Sum of array1 and array2 =', end=' ')
print(array1 + array2)

Sum of array1 and array2 = [27.7  26.41 25.38]


In [148]:
array1[0]

15.5

In [149]:
array1[:2]

array([15.5 , 25.11])

### Array attributes

In [8]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

In [9]:
a.ndim

2

In [10]:
a.size

12

In [11]:
a.shape

(3, 4)

Arrays are typically “homogeneous”, meaning that they contain elements of only one “data type”. 

In [12]:
a.dtype

dtype('int64')

### How to create a basic array

In [15]:
z = np.zeros(2)
print(z)

[0. 0.]


In [16]:
np.ones(2)

array([1., 1.])

In [18]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
#he function empty creates an array whose initial content is random 
# and depends on the state of the memory.
np.empty(5) 

array([ 1.  ,  2.75,  6.  , 10.75, 17.  ])

In [21]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

You can also use **np.linspace()** to create an array with values that are spaced linearly in a specified interval:

In [22]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [10]:
np.random.random((2,3))

array([[0.80569193, 0.48805812, 0.78820543],
       [0.72617487, 0.79677345, 0.13401015]])

**Specifying your data type**

- While the default data type is floating point (np.float64), you can explicitly specify which data type you want using the dtype keyword

- All elements of the array must be of the same type of data.

In [4]:
x = np.ones(2, dtype=np.int64)
print(x)

[1 1]


In [7]:
x = np.ones((2,3), dtype=np.int64)
print(x)

[[1 1 1]
 [1 1 1]]


In [8]:
np.zeros_like(x)

array([[0, 0, 0],
       [0, 0, 0]])

In [9]:
np.ones_like(x)

array([[1, 1, 1],
       [1, 1, 1]])

### Adding, removing, and sorting elements

In [25]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [26]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [48]:
x = np.array([[4, 3],[2, 1]])
y = np.array([[5, 6]])

In [49]:
np.concatenate((x, y), axis=0)

array([[4, 3],
       [2, 1],
       [5, 6]])

In [50]:
np.sort(x)

array([[3, 4],
       [1, 2]])

In [52]:
x

array([[4, 3],
       [2, 1]])

In [51]:
z = np.argsort(x)
print(z)

[[1 0]
 [1 0]]


In [14]:
a = np.array([ [1, 2], [3, 4] ])

# Returns a new 1D (1x2) array with the second row (index 1, axis 0) ([3,4]) removed
# [1, 2]
na = np.delete(a, 1, axis=0)

In [15]:
na

array([[1, 2]])

In [16]:
na > 5

array([[False, False]])

In [17]:
na == [1,2]

array([[ True,  True]])

### Can you reshape an array?

In [29]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [30]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [33]:
b = a.reshape(2, -1)
print(b)

[[0 1 2]
 [3 4 5]]


### How to convert a 1D array into a 2D array (how to add a new axis to an array)

In [53]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [54]:
a2 = a[np.newaxis, :]

In [56]:
a2.shape

(1, 6)

In [61]:
a2

array([[1, 2, 3, 4, 5, 6]])

In [57]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [58]:
b = np.expand_dims(a, axis=1)

In [59]:
b.shape

(6, 1)

In [60]:
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [62]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [63]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [64]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [65]:
x = np.arange(1, 25).reshape(2, 12)

In [66]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [70]:
# split this array into three equally shaped arrays
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

### Basic array operations

In [88]:
array1 = np.array([10, 20, 30, 40])
array2 = np.array([1, 2, 3, 4])

# Some common array operations

print('Adding arrays (array1 + array2)')
print(array1 + array2)

print('\nSubtracting arrays (array1 - array2)')
print(array1 - array2)

print('\nMultiplying arrays (array1 * array2)')
print(array1 * array2)

Adding arrays (array1 + array2)
[11 22 33 44]

Subtracting arrays (array1 - array2)
[ 9 18 27 36]

Multiplying arrays (array1 * array2)
[ 10  40  90 160]


In [89]:
print('\nCalculating dot product of arrays')
print(np.dot(array1, array2))


Calculating dot product of arrays
300


In [18]:
b = np.array([[1, 1], [2, 2]])

In [19]:
b.sum(axis=0)

array([3, 3])

In [20]:
b.sum(axis=1)

array([2, 4])

In [21]:
b.min(axis=0)

array([1, 1])

In [22]:
b.sum(axis=1, keepdims=True) 

array([[2],
       [4]])

### How to get unique items and counts

In [95]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])


In [96]:
unique_values = np.unique(a)

In [97]:
unique_values

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [98]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


**This also works with 2D arrays**

In [102]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [103]:
a_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [104]:
unique_rows = np.unique(a_2d, axis=0)

In [105]:
unique_rows

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [106]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)

In [107]:
unique_rows

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [108]:
indices

array([0, 1, 2])

In [109]:
occurrence_count

array([2, 1, 1])

### Transposing and reshaping a matrix

In [110]:
arr = np.arange(6).reshape((2, 3))

In [112]:
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [111]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

**How to reverse an array**

NumPy’s np.flip() function allows you to flip, or reverse, the contents of an array along an axis

In [115]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

np.flip(arr)

array([8, 7, 6, 5, 4, 3, 2, 1])

A 2D array works much the same way.

In [59]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [60]:
reversed_arr_rows = np.flip(arr_2d, axis=0)

In [61]:
reversed_arr_rows

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

### Flattening arrays
**Notice the difference between flatten and ravel**

In [62]:
a2 = arr_2d.flatten()

In [63]:
a2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [64]:
a2[0] = 100

In [65]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:
a2 = arr_2d.ravel()

In [67]:
a2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [68]:
a2[0] = 200

In [69]:
arr_2d

array([[200,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])