## Numpy


The NumPy package provides tools for mathematical computations in Python. 

Ex: NumPy includes functions to perform common linear algebra operations, fast fourier transforms, and statistics.

**array**

NumPy provides a multidimensional array object, conceptually similar to a list, consisting of an ordered set of elements of the same type.

In [2]:

## Summing arrays vs summing lists.

import numpy as np

list1 = [15.5, 25.11, 19.0]
list2 = [12.2, 1.3, 6.38] 

# Create two 1-dimensional (1D) arrays
# with the elements of the above lists
array1 = np.array(list1)
array2 = np.array(list2)

# Concatenate two lists
print('Concatenation of list1 and list2 =', end=' ')
print(list1 + list2)
print()

# Sum two lists
print('Sum of list1 and list2 =', end=' ')
for i in range(len(list1)):
    print(list1[i] + list2[i], end=' ')  
print('\n')

# Sum two 1D arrays
print('Sum of array1 and array2 =', end=' ')
print(array1 + array2)

Concatenation of list1 and list2 = [15.5, 25.11, 19.0, 12.2, 1.3, 6.38]

Sum of list1 and list2 = 27.7 26.41 25.38 

Sum of array1 and array2 = [27.7  26.41 25.38]


### ndarray

The NumPy array data type is called ndarray, where "nd" stands for N-dimensional and N can be any number of dimensions.

### shape
The shape of an array is a tuple of the lengths of each of the array's dimensions.

### size
The size of an array is the total number of elements in an array.

In [2]:
import numpy as np
# Create 2D array
my_array = np.array([[1, 2, 3], [21, 22, 23]])

print('my_array:')
print(my_array)
print(f'my_array shape: {my_array.shape}')
print(f'my_array size: {my_array.size}')

my_array:
[[ 1  2  3]
 [21 22 23]]
my_array shape: (2, 3)
my_array size: 6


### axis

A NumPy array axis is a direction along each array dimension.

### Array functions.

In [3]:
# Creates a 1D (1, 4) array based off of a list
array1D = np.array([1, 2, 3, 4])

# Creates a 2D (2, 2) array based off of 2 lists
array2D = np.array([ [1, 2], [3, 4] ])

In [4]:
# Creates a 2D (2, 2) array filled with 6s
# [ [6, 6], [6, 6] ]
array_6fill = np.full((2, 2), 6)

In [5]:
array2D = np.array([ [1, 2], [3, 4] ])

# Returns 3: Element located at second row (index 1), first column (index 0)
elem_1_0 = array2D[1, 0]

In [6]:
array2D = np.array([ [1, 2], [3, 4] ])

# Returns a new 1D (1x2) array with the second row (index 1, axis 0) ([3,4]) removed
# [1, 2]
new_a1D = np.delete(array2D, 1, axis=0)

In [7]:
my_array = np.array([2, 4, 1, 3])

# Sorts a 1D array in place
# [1, 2, 3, 4]
my_array.sort(axis=0)

In [8]:
array_7 = np.array([ [7, 7], [7, 7] ])

# Returns a new flattened 1D (1, 4) version of a 2D (2, 2) array
# [7, 7, 7, 7]
array_7flat = array_7.ravel()

In [9]:
array1D = np.array([1, 2, 3, 4])

# Returns a new reshaped 2D (2, 2) version of a 2D (1, 4) array
# [ [1, 2], [3, 4] ]
a_reshaped = array1D.reshape((2,2))

In [10]:
# Returns a new transposed version of a_reshaped
# [[1, 3], [2, 4]]
array1_transposed = a_reshaped.transpose()

In [17]:
# create a 2d array filled with zeros
zar = np.zeros((2,3),dtype=np.int8)
print(zar.view())

[[0 0 0]
 [0 0 0]]


In [18]:
# create a 2d array filled with ones
oar = np.ones((2,3),dtype=np.float32)
print(oar.view())

[[1. 1. 1.]
 [1. 1. 1.]]


In [19]:
nar = np.ones_like(zar)

In [20]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [24]:
car = np.concatenate((nar,zar),axis = 1)
print(car)

[[1 1 1 0 0 0]
 [1 1 1 0 0 0]]


In [25]:
car.astype(np.float32)

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]], dtype=float32)

In [26]:
arr_1d = np.array([1, 2, 3])
print("Original 1D array:", arr_1d)
print("Shape of 1D array:", arr_1d.shape)

Original 1D array: [1 2 3]
Shape of 1D array: (3,)


In [27]:
arr_col_vec = arr_1d[:, np.newaxis]
print("\nColumn vector:", arr_col_vec)
print("Shape of column vector:", arr_col_vec.shape)


Column vector: [[1]
 [2]
 [3]]
Shape of column vector: (3, 1)


### Math operators and functions.

**array1 + array2**	Element-wise addition

**array1 - array2**	Element-wise subtraction

**array1 * array2**	Element-wise multiplication

**array1 / array2**	Element-wise division

**np.sqrt(array1)**	Square root of array elements

**np.log(array1)**	Logarithm of array elements

**np.sin(array1)**	Sine of array elements

**np.max(array1)**	Maximum of array elements

**np.median(array1)**	Median of array elements

**np.std(array1)**	Standard deviation of array elements

**np.var(array1)**	Variance of array elements

**np.dot(array1, array2)**	Dot product of of array1 and array2

**np.matmul(array1, array2)**	Also the dot product of array1 and array2 but with subtle differences from dot() when either array has dimension >= 3

**np.cross(array1, array2)**	Cross product of array1 and array2

In [11]:
import numpy as np

array1 = np.array([10, 20, 30, 40])
array2 = np.array([1, 2, 3, 4])

# Some common array operations

print('Adding arrays (array1 + array2)')
print(array1 + array2)

print('\nSubtracting arrays (array1 - array2)')
print(array1 - array2)

print('\nMultiplying arrays (array1 * array2)')
print(array1 * array2)

print('\nCalculating dot product of arrays')
print(np.dot(array1, array2))

print('\nFinding square root of each element in array1')
print(np.sqrt(array1))

print('\nFinding minimum element in array1')
print(array1.min())

print('\nFinding maximum element in array1')
print(array1.max())

Adding arrays (array1 + array2)
[11 22 33 44]

Subtracting arrays (array1 - array2)
[ 9 18 27 36]

Multiplying arrays (array1 * array2)
[ 10  40  90 160]

Calculating dot product of arrays
300

Finding square root of each element in array1
[3.16227766 4.47213595 5.47722558 6.32455532]

Finding minimum element in array1
10

Finding maximum element in array1
40
